# Generated by Django 4.2.7 on 2025-11-06 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bahan',
            fields=[
                ('id_bahan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_bahan', models.CharField(max_length=100)),
                ('jenis_bahan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('nama_customer', models.CharField(max_length=100)),
                ('nomor_telepon_customer', models.CharField(max_length=50)),
                ('alamat_customer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='detail_pemesanan_produk',
            fields=[
                ('id_detail_pemesanan', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_produk_masuk', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='detail_produksi',
            fields=[
                ('id_detail_produksi', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_produk', models.PositiveIntegerField()),
                ('jumlah_reject', models.PositiveIntegerField(blank=True, null=True)),
                ('jumlah_fg', models.PositiveIntegerField(blank=True, null=True)),
                ('jumlah_bahan_keluar', models.PositiveIntegerField()),
                ('status_qc', models.CharField(choices=[('belum', 'Belum diperiksa'), ('sedang', 'Sedang diperiksa'), ('sudah', 'Sudah diperiksa')], default='belum', max_length=10)),
                ('id_bahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bahan')),
            ],
        ),
        migrations.CreateModel(
            name='produk',
            fields=[
                ('id_produk', models.AutoField(primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=100)),
                ('jenis_produk', models.CharField(max_length=100)),
                ('kapasitas_pallet', models.PositiveIntegerField()),
                ('safety_stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='produksi',
            fields=[
                ('id_produksi', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_produksi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='stok_opname',
            fields=[
                ('id_stok_opname', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_stok_opname', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id_supplier', models.AutoField(primary_key=True, serialize=False)),
                ('nama_supplier', models.CharField(max_length=100)),
                ('nomor_telepon_supplier', models.CharField(max_length=50)),
                ('alamat_supplier', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pengiriman',
            fields=[
                ('id_pengiriman', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_pengiriman', models.DateField()),
                ('nomor_sj', models.CharField(max_length=100)),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customer')),
            ],
        ),
        migrations.CreateModel(
            name='pemesanan',
            fields=[
                ('id_pemesanan', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_pemesanan', models.DateField()),
                ('id_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='pallet_terbuka',
            fields=[
                ('id_pallet_terbuka', models.AutoField(primary_key=True, serialize=False)),
                ('sisa_item', models.PositiveIntegerField()),
                ('tanggal_update', models.DateField()),
                ('id_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.produk')),
            ],
        ),
        migrations.CreateModel(
            name='pallet_penuh',
            fields=[
                ('id_pallet_penuh', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_pallet_penuh', models.PositiveIntegerField()),
                ('tanggal_event', models.DateField()),
                ('event_type', models.CharField(choices=[('AUTO', 'Auto Close'), ('MANUAL', 'Manual Close')], default='AUTO', max_length=10)),
                ('id_detail_pemesanan_produk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.detail_pemesanan_produk')),
                ('id_detail_produksi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_menutup', to='inventory.detail_produksi')),
                ('id_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.produk')),
            ],
        ),
        migrations.CreateModel(
            name='kebutuhan_pallet',
            fields=[
                ('id_kebutuhan', models.AutoField(primary_key=True, serialize=False)),
                ('kebutuhan', models.PositiveIntegerField()),
                ('mm_per_roll', models.PositiveIntegerField(default=0)),
                ('id_bahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bahan')),
            ],
        ),
        migrations.CreateModel(
            name='detail_so_produk',
            fields=[
                ('id_detail_so_produk', models.AutoField(primary_key=True, serialize=False)),
                ('stok_fisik_produk', models.PositiveIntegerField()),
                ('id_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.produk')),
                ('id_stok_opname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stok_opname')),
            ],
        ),
        migrations.CreateModel(
            name='detail_so_bahan',
            fields=[
                ('id_detail_so_bahan', models.AutoField(primary_key=True, serialize=False)),
                ('stok_fisik_bahan', models.PositiveIntegerField()),
                ('id_bahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bahan')),
                ('id_stok_opname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stok_opname')),
            ],
        ),
        migrations.AddField(
            model_name='detail_produksi',
            name='id_produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.produk'),
        ),
        migrations.AddField(
            model_name='detail_produksi',
            name='id_produksi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.produksi'),
        ),
        migrations.CreateModel(
            name='detail_pengiriman',
            fields=[
                ('id_detail_pengiriman', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_produk_dikirim', models.PositiveIntegerField()),
                ('id_pengiriman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pengiriman')),
                ('id_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.produk')),
            ],
        ),
        migrations.AddField(
            model_name='detail_pemesanan_produk',
            name='id_pemesanan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pemesanan'),
        ),
        migrations.AddField(
            model_name='detail_pemesanan_produk',
            name='id_produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.produk'),
        ),
        migrations.CreateModel(
            name='detail_pemesanan_bahan',
            fields=[
                ('id_detail_pemesanan', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_bahan_masuk', models.PositiveIntegerField()),
                ('id_bahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bahan')),
                ('id_pemesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pemesanan')),
            ],
        ),
    ]
